// <auto-generated />
using LibraryManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagementSystem.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20250225005809_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagementSystem.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CopiesAvailable")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "مؤلف 1",
                            CopiesAvailable = 5,
                            ISBN = "123456",
                            Title = "كتاب 1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "مؤلف 2",
                            CopiesAvailable = 3,
                            ISBN = "789012",
                            Title = "كتاب 2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "مؤلف 3",
                            CopiesAvailable = 2,
                            ISBN = "345678",
                            Title = "كتاب 3"
                        },
                        new
                        {
                            Id = 4,
                            Author = "مؤلف 1",
                            CopiesAvailable = 4,
                            ISBN = "901234",
                            Title = "كتاب 4"
                        },
                        new
                        {
                            Id = 5,
                            Author = "مؤلف 2",
                            CopiesAvailable = 1,
                            ISBN = "567890",
                            Title = "كتاب 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
